[project]
name = "mp-osc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "ndi-python>=5.1.1.5",
    "numpy<2",
    "psutil>=7.2.1",
]
